### ISSUE TITLE
Seren 2.0.10 

### ISSUE THREAD

**Issue by fiddelsticks** [nixgates/nixgates.github.io#2]
Im running on apple tvOS 14.3 and kodi 17.6 installed.  Seren has been working fine until today.  tried updated to there newest release and now I get Error.  Seren, the dependency on script.module.pycryptodome version 3.4.3 could not be satisfied.  so I tried to use the kodi 19 matrix.  when adding there GitHub source nothing shows in the file manager.  my Apple TV is not jailbroken and I use Xcode to side load this.. direction please.

**Comment by frizby66** [comment]
Latest update fixes this (has for me).

**Comment by drinfernoo** [comment]
This has been fixed, months ago.
