### ISSUE TITLE
Movies do not sync

### ISSUE THREAD

**Issue by johndono** [nixgates/nixgates.github.io#5]
I have latest version of Seren 2.16 Matrix+1, using Firestick and Kodi 19
I have found Movies are not syncing with Trakt

**Comment by drinfernoo** [comment]
Please open this issue on the proper repository: https://github.com/nixgates/plugin.video.seren/issues/

And make sure to include a debug log, and any of the other information requested by the bug report template. You've given no information regarding your issue.
