### ISSUE TITLE
Trakt AND RD get messed up by Seren

### ISSUE THREAD

**Issue by npmstart-pray** [nixgates/nixgates.github.io#7]
And I believe Orion may have something to do with it. 
I'm not sure what crashes - Seren or kodi - because logs don't survive reboots, but when I scrape for something, my system reboots when the Orion pop up appears on screen. Reauth-ing trakt and/or RD is getting tiresome. Can y'all help a brother out soon please?

**Comment by drinfernoo** [comment]
Open this issue on the Seren issue tracker: https://www.github.com/nixgates/plugin.video.seren/issues/

And be sure to include all of the requested information, **including a log file**.

**Comment by npmstart-pray** [comment]
Clean logs because kodi reboots. Maybe I put that on Reddit.

**Comment by drinfernoo** [comment]
Get the log before Kodi reboots.

**Comment by npmstart-pray** [comment]
No time, because there’s no telling of/when it will happen.
